[Interface]
Bouncing = 3
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = aHnexoO/G9VnP5Bb5NXtscaOCKGyj9kG3BOV/YUXSWs= Address = 10.2.0.2/32 DNS = 10.2.0.1
[Peer]
JP-FREE#21
PublicKey = xrZTJ9U7GHo834PN1sckR4RuLjP/Sy0jb2d0z1pLgzU= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 37.19.205.198:51820
PersistentKeepalive = 25