[Interface]
Bouncing = 3
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = GPcy+LxwhF4sgOayWoVwyN0SCPpBeh2t01axpvm7c1Y= Address = 10.2.0.2/32 DNS = 10.2.0.1
[Peer]
MX-FREE#7
PublicKey = G1H7jHJjOxnNXy0GPQNRT5ikSESyagGePfG1COP+4Hs= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 149.88.17.182:51820
PersistentKeepalive = 25