[Interface]
Bouncing = 0
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = YFPG70kzzd9iPgrXbEz5ebcaV97xYZalso5AunGoMHI= Address = 10.2.0.2/32 DNS = 10.2.0.1
[Peer]
NL-FREE#126
PublicKey = WM3qIvkeeD+ouwERuqCVZds82cvh+vsGQPG6ibBGDGA= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 185.107.56.69:51820
PersistentKeepalive = 25