[Interface]
Bouncing = 2
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = kKi/ExTZ0hZzVQF7LgIihDPiJ5tj+PRZayvXiQQtdGM= Address = 10.2.0.2/32, 2a07:b944::2:2/128 DNS = 10.2.0.1, 2a07:b944::2:1
[Peer]
NL-FREE#104
PublicKey = URpeZxtyUXAUUA0MWcFdCSa7F+MvchJ4eNSJUetKEGk= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 212.8.253.137:51820
Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
Endpoint = [2a00:7c80:0:3c7::10]:51820
PersistentKeepalive = 25