[Interface]
Bouncing = 0
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = 4OdQSsuwxlaoEX9r88wQqjZRSx5wYEOUU0wwiRck7XQ= Address = 10.2.0.2/32, 2a07:b944::2:2/128 DNS = 10.2.0.1, 2a07:b944::2:1
[Peer]
NO-FREE#6
PublicKey = 84dSFrHWsJr34E8GWyXZsxFourH7+vbjUoJWlZmS13I= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 95.173.205.165:51820
Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
Endpoint = [2a02:6ea0:5601:6472::10]:51820
PersistentKeepalive = 25