[Interface]
Key for FREE servers
Bouncing = 3
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = eJ3qqD6a+XqsMBschc1t77GT2v6DWfMh/LXHpi/+0Xs= Address = 10.2.0.2/32, 2a07:b944::2:2/128 DNS = 10.2.0.1, 2a07:b944::2:1
[Peer]
US-FREE#44
PublicKey = 4wqoqnWaoR8FLWkihmN4DVma/8lFn1fXQMRVs/4TD0A= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 37.19.221.196:51820
Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
Endpoint = [2a02:6ea0:e00a:2239::10]:51820
PersistentKeepalive = 25
