[Interface]
Bouncing = 3
NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = mLNloTcCy52N/SiXdt4U2VUYHhSiuyzbQg+UCM0h718= Address = 10.2.0.2/32 DNS = 10.2.0.1
[Peer]
SG-FREE#18
PublicKey = whEECgH2k+DQjnLR/Vf/Chm7pLsxCnTd9fzCRcWFqzM= AllowedIPs = 0.0.0.0/0, ::/0 Endpoint = 103.216.221.72:51820
PersistentKeepalive = 25